const QUIZZES=[
{id:'either',icon:'♡',title:'生活里的小选择',desc:'一些很小的选择，也会悄悄照见两个人的日常。',type:'choice',soft:'#f6e2df',rule:'选最接近自己的答案；没有合适的，就写下自己的想法。',questions:[
['周末只有半天见面，你更想？',['出门逛逛','宅家黏着']],['旅行目的地更心动？',['海边','山里']],['约会主食只能选一个？',['火锅','烧烤']],['晚上一起消磨时间？',['看电影','刷综艺']],['散步最舒服的时间？',['傍晚','深夜']],['旅行拍照风格？',['拍很多','少拍一点']],['睡觉更舒服？',['抱着睡','各睡各的']],['礼物更戳你？',['实用','有仪式感']],['异地时更喜欢？',['打字聊天','打电话']],['旅行节奏？',['多打卡','慢慢晃']],['纪念日安排？',['提前计划','当天随性']],['有矛盾时？',['当天说清','冷静后聊']],['吃到特别好吃的东西？',['一定分一口','各吃各的']],['见面第一反应？',['先抱一下','先说一堆话']],['情侣装？',['偶尔可以','不太想穿']],['逛街方式？',['有目标地买','随便晃']],['普通约会地点？',['商场','公园']],['睡前状态？',['聊到困','安静陪着']],['选酒店更看重？',['房间舒服','位置方便']],['回消息习惯？',['快回更开心','有空回就行']],['一起做饭？',['两个人一起','一人做一人等']],['下雨天约会？',['照样出去','改室内']],['突然多一天假？',['马上出去玩','在家补觉']],['惊喜方式？',['突然出现','提前商量']]]},
{id:'guess',icon:'⌁',title:'猜我会选什么',desc:'固定选项，真的可以核验命中率',type:'choice',soft:'#e5eef3',rule:'你先替对方猜一遍；对方本人再用同一套题作答，之后比较两个 JSON。',questions:[
['我理想中的约会更像哪一种？',['吃好吃的','散步聊天','宅家','短途旅行']],['我心情差时最希望你怎么做？',['抱抱','听我吐槽','给我空间','帮我解决']],['我收到哪类礼物最开心？',['实用东西','吃的','小惊喜','手写/纪念']],['我旅行最在意什么？',['吃','住','景点','拍照']],['我更容易因为什么不开心？',['被忽略','计划被打乱','说话语气','小事积累']],['我更喜欢哪种联系？',['消息不断','固定电话','想起就聊','见面补回来']],['我最喜欢哪种肢体接触？',['牵手','抱抱','亲亲','靠着']],['突然放三天假，我最可能？',['去旅行','回家休息','找好吃的','临时决定']],['我更可能被哪种方式哄好？',['讲道理','认错','逗笑','给点时间']],['我最喜欢你发什么给我？',['日常碎片','自拍','搞笑东西','想我的话']],['我对纪念日的态度？',['很看重','简单过','想起来就过','不太在意']],['我更喜欢的周末？',['睡懒觉','出门玩','吃一顿好的','一起做点事']],['我更可能因为什么吃醋？',['前任','异性朋友','被冷落','基本不吃醋']],['我选宠物会选？',['猫','狗','小型宠物','暂时不养']],['我最受不了旅行里的哪件事？',['早起','排队','走太多','行程乱']],['我更喜欢的照片？',['正经合照','抓拍','搞怪照','风景带人']],['我更想一起学什么？',['做饭','运动','拍照','一门新技能']],['我更喜欢哪种惊喜？',['突然见面','小礼物','带我去吃','安排一整天']],['我觉得我们谁更黏人？',['A方','B方','差不多','看阶段']],['现在最想和你一起完成？',['一次旅行','一顿大餐','一次合照','一整天宅家']]]},
{id:'lights',icon:'◉',title:'恋爱红黄绿灯',desc:'轻松聊边界，重点看不同颜色',type:'choice',soft:'#f6ead7',rule:'绿＝可以，黄＝看情况，红＝接受不了。差异大的题最值得聊。',questions:['偶尔查看对方手机','和异性朋友单独吃饭','和前任保持普通联系','忙一天只简单回几条消息','吵架后想独处一会儿','把合照发朋友圈','未经同意发对方丑照','互相知道手机密码','临时取消已经约好的见面','忘记普通纪念日','忘记生日','单独和朋友旅行','和朋友聚会到很晚','保留自己的私人空间','未经允许翻聊天记录','情侣之间长期共享定位','异地时一天只认真聊一次','在公共场合有亲密动作','把两人的矛盾详细讲给朋友','生气时先睡一晚第二天再谈'].map(q=>[q,['绿灯 可以','黄灯 看情况','红灯 不接受']])},
{id:'whatif',icon:'✦',title:'如果我们……',desc:'脑洞情景题，很容易聊歪',type:'text',soft:'#ebe4f5',rule:'没有标准答案。每次玩 3—5 题就够。',questions:['如果我们突然中了 100 万，第一笔钱会花在哪？','如果明天突然多出三天假，我们会去哪？','如果只能在一个城市生活十年，会选哪里？','如果一起被困荒岛，你觉得谁先崩溃？','如果家里突然多了一只猫，会给它取什么名字？','如果交换身体一天，你最想体验什么？','如果回到第一次见面那天，你会偷偷提醒自己什么？','如果只能重复一次约会，你会选哪次？','如果以后一起开一家小店，会开什么？','如果突然停电一整晚，我们会怎么过？','如果一起穿越古代，你觉得我们靠什么谋生？','如果要一起学一项新技能，你想学什么？','如果今晚能瞬移到任何地方睡一晚，你想去哪？','如果新家只能留一个超大空间，你会做成什么？','如果一个月不能点外卖，我们最先学会做哪道菜？','如果必须一起参加一个综艺，会选哪种？','如果能提前看见十年后的一天，你最想看哪个画面？','如果可以给“我们”加一个隐藏技能，你会加什么？','如果要给我们的恋爱养一个吉祥物，它会是什么？','如果明天醒来我们共同多了一项超能力，你希望是什么？']},
{id:'rank',icon:'≋',title:'情侣排行榜',desc:'看看彼此真正的优先级',type:'rank',soft:'#e2f1e8',rule:'用 ↑ ↓ 调整顺序，第一名放最上面。手机和平板都比拖拽稳定。',questions:[['约会方式怎么排？',['吃饭','散步','电影','逛街','宅家']],['旅行内容怎么排？',['美食','景点','酒店','拍照','闲逛']],['礼物类型怎么排？',['花','零食','实用品','首饰','手写信']],['肢体接触怎么排？',['牵手','拥抱','亲亲','靠肩','摸头']],['睡前活动怎么排？',['聊天','看剧','刷视频','听歌','安静躺']],['周末安排怎么排？',['吃好吃的','逛商场','去公园','周边游','在家']],['恋爱仪式怎么排？',['生日','纪念日','节日','突然惊喜','日常小礼物']],['酒店条件怎么排？',['位置','干净','隔音','床舒服','房间好看']],['被哄方式怎么排？',['抱抱','听我说','逗我笑','给空间','解决问题']],['一起生活最看重怎么排？',['卫生','作息','沟通','钱','吃饭习惯']]]},
{id:'memory',icon:'⌛',title:'我们的回忆考试',desc:'同一段恋爱，可能有两个版本',type:'text',soft:'#f5e1e8',rule:'答案不一致也不判输赢，各自讲讲记得的版本。',questions:['第一次聊天是谁先主动的？','第一次见面在哪里？','第一次见面时对方穿了什么？','第一次一起吃的是什么？','第一次比较正式的约会去了哪里？','第一次牵手是谁先伸手的？','第一次送给对方的礼物是什么？','第一次一起看的电影或剧是什么？','第一次拍合照是什么时候？','第一次一起旅行去了哪里？','你记得第一次明显吃醋是什么事吗？','哪一次约会时间最长？','哪一次见面最舍不得分开？','我们一起吃过次数最多的东西是什么？','最早出现的一个专属称呼是什么？','第一次觉得“TA 好像真的喜欢我”是什么时候？','哪次聊天聊得特别晚？','哪件小事让你第一次觉得对方很可爱？','我们最常去的一家店或一个地方是什么？','如果只能保留一段共同回忆，你会选哪一段？']},
{id:'who',icon:'↔',title:'谁更像……',desc:'A 方 / B 方 / 差不多，避免视角混乱',type:'choice',soft:'#e6eaf6',rule:'先约定谁是 A 方、谁是 B 方。两个人分别答，看判断是否一致。',questions:['谁更容易赖床？','谁更容易迷路？','谁更爱吃醋？','谁更嘴硬？','谁更容易心软？','谁更会哄人？','谁更容易忘东西？','谁花钱更冲动？','谁更喜欢拍照？','谁更容易饿？','谁更容易困？','谁旅行时更容易累？','谁更会做攻略？','谁更可能临时改计划？','谁更黏人？','谁吵架后更想赶快和好？','谁更会偷偷准备惊喜？','谁更适合养猫？','谁更适合养狗？','谁更容易把东西随手乱放？','谁更会照顾人？','谁更容易被美食收买？','谁老了以后更爱念叨？','谁更可能半夜突然说“我饿了”？'].map(q=>[q,['A 方','B 方','差不多']])},
{id:'cohabit',icon:'⌂',title:'同居模拟',desc:'提前看看生活习惯会不会打架',type:'choice',soft:'#eee9db',rule:'选真实习惯，别选“理想中的自己”。',questions:[['空调通常想开多少？',['24℃及以下','25—26℃','27℃以上']],['理想睡觉时间？',['23点前','23—1点','1点后']],['闹钟响了以后？',['马上起','再躺10分钟','能拖就拖']],['床上吃东西？',['可以','偶尔','不接受']],['衣服怎么洗？',['当天','攒两三天','快没衣服再洗']],['外卖盒怎么处理？',['吃完就扔','晚点一起扔','第二天']],['家里多乱会开始收拾？',['一点乱就收','明显乱了','实在受不了']],['平时吃饭？',['多做饭','做饭外卖各半','多外卖']],['洗碗时机？',['吃完马上','歇会儿','攒一会儿']],['洗澡时间？',['回家就洗','睡前','看当天安排']],['周末起床？',['8点前','9—10点','自然醒']],['朋友来家里？',['很欢迎','提前说就行','不太喜欢']],['买家居用品？',['实用优先','好看优先','性价比优先']],['冰箱收纳？',['分类整齐','大概分区','放得下就行']],['零食怎么分？',['各自一份','全部共享','特别喜欢的分开']],['有人抢被子怎么办？',['再加一床','继续抢','一开始就各盖各的']],['一方突然想安静？',['直接给空间','先问一句','陪在旁边']],['家务怎么分？',['固定分工','谁有空谁做','一起做']],['新家风格？',['清爽极简','温馨柔软','东西多但有生活感']],['最优先谈清哪件事？',['钱','家务','作息','私人空间']]]},
{id:'pref',icon:'◇',title:'恋爱偏好三档',desc:'喜欢 / 可以 / 不喜欢，一眼看差异',type:'choice',soft:'#dff0ef',rule:'最有价值的是“一个很喜欢、一个不喜欢”的项目。',questions:['每天说早安或晚安','突然打电话','长时间视频','情侣头像','情侣昵称','情侣装','偶尔公开秀恩爱','一起拍大头贴','一起做饭','一起逛超市','一起做家务','喂对方吃东西','出门经常牵手','抱着睡','睡前聊天','认真过纪念日','节日送礼物','偶尔写小纸条或长消息','异地突然去见对方','一起做旅行攻略','长期共享定位','分享每天吃了什么','互相拍很多照片','一起养宠物'].map(q=>[q,['很喜欢','可以','不喜欢']])},
{id:'sweet',icon:'♥',title:'心动按钮',desc:'0—5 分找到对方真正吃哪一套',type:'scale',soft:'#f7e4dd',rule:'0＝无感，5＝超喜欢。按真实感觉打，不必把“好事”都打高分。',questions:['见面时突然抱你','出门主动牵你的手','记得你随口说过的小事','给你拍好看的照片','记得你常喝的饮料口味','突然带你去吃喜欢的东西','你困的时候给你盖被子','心情不好时安静陪你','主动帮你解决一个麻烦','临时准备一个小礼物','给你写一段比较长的话','旅行前主动做好攻略','在人多的地方一直牵着你','主动夸你好看','给你留最后一口喜欢吃的东西','半夜陪你聊天','看到好玩的第一时间发给你','主动报备当天行程','安排一整天不告诉你的惊喜','各忙各的但一直挂着电话']},
{id:'odd',icon:'?',title:'离谱选择题',desc:'荒唐一点，答案反而很真',type:'choice',soft:'#eee4f3',rule:'别想太久，按第一反应选。',questions:[['如果对象变成猫一天，你会？',['抱着到处走','拍一百张照片','让TA自己玩','先买猫罐头']],['如果我们只能用一种方式联系一周？',['文字','语音','视频','写信']],['必须保留一个共同纪念物？',['聊天记录','合照','礼物','车票/小票']],['一起穿越古代，第一份工作？',['摆摊','开客栈','写字算账','直接逃荒']],['我们共同拥有一种超能力？',['瞬移','读天气','永不迷路','吃不胖']],['对象突然变成拇指大小一天？',['放口袋里','做小房子','带出去玩','全程保护']],['只能重复一种约会一年？',['吃饭','散步','看电影','宅家']],['家里只能有一种零食？',['薯片','巧克力','水果','坚果']],['如果我们一起参加综艺？',['旅行','做饭','密室','恋爱观察']],['两个人互换手机壁纸一个月？',['甜蜜合照','对方丑照','宠物','风景']],['突然停电一晚？',['聊天','打牌','出门散步','直接睡']],['被困机场 8 小时？',['找吃的','找地方睡','逛完所有店','一起看剧']],['只能养一种奇怪宠物？',['鸭子','刺猬','羊驼','都不要']],['一起开一家小店？',['咖啡店','小饭馆','书店','宠物店']],['如果我们的恋爱是一部剧？',['喜剧','爱情片','公路片','纪录片']],['对象突然学会读心 10 分钟？',['立刻跑','随便读','先谈规则','我也要学']],['只能带一样东西去荒岛？',['手机','刀具','打火机','对方负责选']],['今晚能瞬移去睡一晚？',['海边','山里','大城市酒店','还是自己的床']],['如果我们有一个共同机器人？',['做饭','打扫','做攻略','哄人']],['只能把一种日常永久升级？',['睡眠','吃饭','旅行','拍照']]]},
{id:'talk',icon:'☾',title:'慢慢真心话',desc:'不急着得出结论，只把心里的话多留一会儿。',type:'text',soft:'#e3efec',rule:'可以跳题。写一点就够，适合睡前慢慢聊。',questions:['最近一次觉得我很可爱是什么时候？','最近有没有一件我做得比你预期更好的事？','我有什么小习惯是你其实挺喜欢的？','最近最想和我一起做什么？','最近有没有一句话想听我多说一点？','最近哪一次聊天你印象最深？','有没有哪件小事想让我稍微改一点？','最近一次特别想抱我是什么时候？','有没有一个地方最近很想和我一起去？','哪一种相处状态让你最放松？','我什么时候最容易让你觉得安心？','最近一次突然想我是什么时候？','有没有一件你觉得我可能没发现、但你很在意的小事？','如果明天能一起做一件事，你会选什么？','最近有没有一句一直想说但没找到机会的话？','你觉得我们现在最舒服的一种日常是什么？','最近最喜欢我的哪张照片？','最近一次因为我笑出来是什么时候？','你觉得我最近哪里变得更好了？','有没有一种小礼物其实你挺想收到？','你觉得我们最像哪一种动物组合？','如果给最近的恋爱状态打 0—10 分，你会打几分？为什么？','最近最期待我们一起发生什么？','今晚睡前最想听我对你说哪句话？']}
];

const STORE='coupleSleepQuiz.v2';
const app=document.querySelector('#app');
let state=load();
let route={view:'home',quizId:null,index:0};
function load(){try{return JSON.parse(localStorage.getItem(STORE))||{name:'',answers:{},rank:{}}}catch{return{name:'',answers:{},rank:{}}}}
function save(){localStorage.setItem(STORE,JSON.stringify(state))}
function quiz(id){return QUIZZES.find(q=>q.id===id)}
function key(qid,i){return `${qid}:${i}`}
function answeredCount(q){return q.questions.reduce((n,_,i)=>n+(state.answers[key(q.id,i)]!==undefined&&state.answers[key(q.id,i)]!==''?1:0),0)}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function showToast(msg){const t=document.createElement('div');t.className='toast';t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),1500)}
function home(){route={view:'home',quizId:null,index:0};const done=QUIZZES.filter(q=>answeredCount(q)===q.questions.length).length;app.innerHTML=`<section class="hero"><div class="eyebrow">COUPLE · SLEEP QUIZ</div><h1>今晚玩哪个？</h1><p>12 套情侣睡前小游戏。手机竖屏、平板横竖屏都能直接点，进度自动保存在当前设备。</p><div class="mini-row"><span class="pill">12 种玩法</span><span class="pill">已完成 ${done}/12</span><span class="pill">当前进度保存在本机</span></div></section><section class="grid">${QUIZZES.map((q,i)=>{const n=answeredCount(q),pct=Math.round(n/q.questions.length*100);return `<button class="quiz-card" style="--soft:${q.soft}" data-open="${q.id}"><span class="icon">${q.icon}</span><span><h3>${q.title}</h3><p>${q.desc}</p><div class="progress-note">${n?`进度 ${n}/${q.questions.length} · ${pct}%`:'未开始'}</div></span><span class="chev">›</span></button>`}).join('')}</section><div class="section-title">答完以后</div><button class="quiz-card" data-results="1"><span class="icon" style="background:#eee7e3">⇩</span><span><h3>我的答卷</h3><p>查看全部作答，并导出一个 JSON 文件发给对方或 ChatGPT。</p></span><span class="chev">›</span></button><div class="footer-note">当前进度本机保存 · 完成记录可上传云端</div>`;app.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openQuiz(b.dataset.open));app.querySelector('[data-results]').onclick=results}
function openQuiz(id,index=0){const q=quiz(id);route={view:'quiz',quizId:id,index:Math.max(0,Math.min(index,q.questions.length-1))};renderQuestion()}
function renderQuestion(){const q=quiz(route.quizId),i=route.index,total=q.questions.length,k=key(q.id,i),val=state.answers[k];const item=q.questions[i];const question=Array.isArray(item)?item[0]:item;const options=Array.isArray(item)?item[1]:null;let control='';if(q.type==='choice'){control=`<div class="options ${options.length<=4?'two-col':''}">${options.map((o,idx)=>`<button class="option ${val===idx?'selected':''}" data-opt="${idx}"><span class="letter">${String.fromCharCode(65+idx)}</span>${esc(o)}</button>`).join('')}</div>`}else if(q.type==='text'){control=`<textarea class="textarea" data-text placeholder="写下第一反应……">${esc(val||'')}</textarea>`}else if(q.type==='scale'){control=`<div class="scale">${[0,1,2,3,4,5].map(n=>`<button data-scale="${n}" class="${val===n?'selected':''}">${n}</button>`).join('')}</div><div class="scale-note"><span>无感</span><span>超喜欢</span></div>`}else if(q.type==='rank'){let arr=state.rank[k]||[...options];state.rank[k]=arr;control=`<div class="rank-list">${arr.map((o,idx)=>`<div class="rank-item"><span class="rank-num">${idx+1}</span><span>${esc(o)}</span><span class="rank-controls"><button class="smallbtn" data-up="${idx}" ${idx===0?'disabled':''}>↑</button><button class="smallbtn" data-down="${idx}" ${idx===arr.length-1?'disabled':''}>↓</button></span></div>`).join('')}</div>`}app.innerHTML=`<div class="topbar"><button class="back" data-home>‹ 首页</button><div class="title-wrap"><small>${q.icon} ${q.rule}</small><h2>${q.title}</h2></div></div><div class="progress-wrap"><div class="progress-bar" style="width:${((i+1)/total)*100}%"></div></div><section class="question-card"><div class="qnum">QUESTION ${String(i+1).padStart(2,'0')} / ${String(total).padStart(2,'0')}</div><h3>${esc(question)}</h3>${control}</section><div class="nav"><button class="ghost" data-prev ${i===0?'disabled':''}>上一题</button><button class="primary" data-next>${i===total-1?'完成这套':'下一题'}</button></div>`;app.querySelector('[data-home]').onclick=home;app.querySelector('[data-prev]').onclick=()=>openQuiz(q.id,i-1);app.querySelector('[data-next]').onclick=()=>{if(q.type==='rank'){state.answers[k]=state.rank[k];save()}if(i===total-1)quizResult(q);else openQuiz(q.id,i+1)};if(q.type==='choice')app.querySelectorAll('[data-opt]').forEach(b=>b.onclick=()=>{state.answers[k]=Number(b.dataset.opt);save();renderQuestion()});if(q.type==='text'){const ta=app.querySelector('[data-text]');ta.oninput=()=>{state.answers[k]=ta.value;save()}}if(q.type==='scale')app.querySelectorAll('[data-scale]').forEach(b=>b.onclick=()=>{state.answers[k]=Number(b.dataset.scale);save();renderQuestion()});if(q.type==='rank'){app.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>moveRank(k,Number(b.dataset.up),-1));app.querySelectorAll('[data-down]').forEach(b=>b.onclick=()=>moveRank(k,Number(b.dataset.down),1))}}
function moveRank(k,idx,dir){const arr=state.rank[k],j=idx+dir;if(j<0||j>=arr.length)return;[arr[idx],arr[j]]=[arr[j],arr[idx]];state.rank[k]=arr;state.answers[k]=arr;save();renderQuestion()}
function answerLabel(q,i){const item=q.questions[i],v=state.answers[key(q.id,i)];if(v===undefined||v==='')return '未作答';if(q.type==='choice')return item[1][v]??'未作答';if(q.type==='scale')return `${v} / 5`;if(q.type==='rank')return Array.isArray(v)?v.join(' ＞ '):'未排序';return v}
function quizResult(q){const n=answeredCount(q);let extra='';if(q.type==='scale'){const vals=q.questions.map((_,i)=>state.answers[key(q.id,i)]).filter(v=>typeof v==='number');if(vals.length){const avg=(vals.reduce((a,b)=>a+b,0)/vals.length).toFixed(1);const top=q.questions.map((x,i)=>[x,state.answers[key(q.id,i)]]).filter(x=>x[1]>=4).slice(0,5).map(x=>x[0]);extra=`<p>平均心动值 <b>${avg}/5</b>${top.length?`。你的高甜按钮包括：${top.map(esc).join('、')}。`:''}</p>`}}app.innerHTML=`<div class="topbar"><button class="back" data-home>‹ 首页</button></div><section class="result"><div class="eyebrow">COMPLETE</div><h2>${q.title}</h2><p>完成 ${n}/${q.questions.length} 题。${n<q.questions.length?'还有题目没答也没关系，可以之后继续。':'这一套已经答完。'}</p>${extra}<div class="summary-list">${q.questions.slice(0,6).map((it,i)=>`<div class="summary-item"><b>${esc(Array.isArray(it)?it[0]:it)}</b><span>${esc(answerLabel(q,i))}</span></div>`).join('')}${q.questions.length>6?`<div class="muted">这里只预览前 6 题，完整内容在“我的答卷”里。</div>`:''}</div><div class="result-actions"><button class="primary" data-all>查看我的答卷</button><button class="ghost" data-again>返回这套问卷</button></div></section>`;app.querySelector('[data-home]').onclick=home;app.querySelector('[data-all]').onclick=results;app.querySelector('[data-again]').onclick=()=>openQuiz(q.id,0)}
function results(){route={view:'results'};const total=QUIZZES.reduce((n,q)=>n+q.questions.length,0),done=QUIZZES.reduce((n,q)=>n+answeredCount(q),0);app.innerHTML=`<div class="topbar"><button class="back" data-home>‹ 首页</button><div class="title-wrap"><small>MY ANSWERS</small><h2>我的答卷</h2></div></div><section class="result"><h2>${done} / ${total}</h2><p>已作答题目。导出的 JSON 会包含题目、文字答案和选项文字，方便另一方或 ChatGPT 直接读取。</p><div class="summary-list">${QUIZZES.map(q=>`<div class="summary-item"><b>${q.icon} ${q.title}</b><span>${answeredCount(q)} / ${q.questions.length}</span></div>`).join('')}</div><div class="result-actions"><button class="primary" data-export>导出 JSON 答卷</button><button class="ghost" data-copy>复制答卷文本</button><button class="ghost" data-reset>清空全部进度</button></div></section>`;app.querySelector('[data-home]').onclick=home;app.querySelector('[data-export]').onclick=exportJSON;app.querySelector('[data-copy]').onclick=copyText;app.querySelector('[data-reset]').onclick=()=>{if(confirm('确定清空当前设备上的全部答案吗？')){localStorage.removeItem(STORE);state=load();home()}}}
function buildExport(){return {title:'情侣睡前问卷答卷',version:2,exportedAt:new Date().toISOString(),quizzes:QUIZZES.map(q=>({id:q.id,title:q.title,answers:q.questions.map((it,i)=>({question:Array.isArray(it)?it[0]:it,answer:answerLabel(q,i)}))}))}}
function exportJSON(){const blob=new Blob([JSON.stringify(buildExport(),null,2)],{type:'application/json;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`情侣睡前问卷答卷_${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);showToast('答卷已生成')}
async function copyText(){const d=buildExport();const text=d.quizzes.map(q=>`【${q.title}】\n`+q.answers.filter(a=>a.answer!=='未作答').map(a=>`${a.question}：${a.answer}`).join('\n')).join('\n\n');try{await navigator.clipboard.writeText(text);showToast('已复制答卷文本')}catch{showToast('浏览器未允许复制')}}
window.addEventListener('popstate',home);home();