// Consolidated interaction + realtime stability runtime.
// Draft contents stay local; only an editing marker is shared until confirmation.
(function(){
  const BG_GRACE=60000,ONLINE_MS=9000,HEARTBEAT=3000,STALE_CLAIM=90000,RESUME_MAX=7*24*60*60*1000;
  const RESUME_PREFIX='coupleSleepQuiz.duo.resume.v2.',CUSTOM_KIND='custom';
  let bgTimer=null,bgSuspended=false,bgDisconnecting=false,watchdog=null,lastPartner=null,seenPartner=false,lastClaim=0,lastBeat=0,connectGen=0,connecting=null,resyncTimer=null,pendingPublishTimer=null;

  window.duoNavApplying=false;window.duoNavPending=null;window.duoNavDirty=false;window.duoNavStarting=false;
  window.duoNavClock=0;window.duoNavApplied={clock:0,clientId:''};window.duoNavWanted={view:'home',quizId:null,index:0};

  function drafts(){
    if(!state.drafts||typeof state.drafts!=='object')state.drafts={};
    for(const n of ['text','custom','customOpen','rank'])if(!state.drafts[n]||typeof state.drafts[n]!=='object')state.drafts[n]={};
    return state.drafts;
  }
  const kOf=(qid,i)=>`${qid}:${i}`;
  const isCustom=v=>!!(v&&typeof v==='object'&&v.kind===CUSTOM_KIND&&typeof v.text==='string');
  const customText=v=>isCustom(v)?String(v.text||'').trim():'';
  function saveLocal(){try{if(duo.active)duoRoomStoreSave();else localStorage.setItem(STORE,JSON.stringify(state))}catch{}}
  function pendingKey(){
    if(route.view!=='quiz'||!route.quizId)return null;
    const q=quiz(route.quizId);if(!q)return null;
    const k=kOf(q.id,route.index),d=drafts();
    if(Object.prototype.hasOwnProperty.call(d.text,k))return k;
    if(d.customOpen[k]&&Object.prototype.hasOwnProperty.call(d.custom,k))return k;
    if(Object.prototype.hasOwnProperty.call(d.rank,k)){
      const a=state.answers?.[k];if(!Array.isArray(a)||JSON.stringify(a)!==JSON.stringify(d.rank[k]))return k;
    }
    return null;
  }
  function publishPending(){
    clearTimeout(pendingPublishTimer);
    pendingPublishTimer=setTimeout(()=>{
      if(duo.active&&duo.accepted&&duo.mqtt?.connected)duoPublishState().catch(()=>{});
    },100);
  }

  window.choiceAnswerIsCustom=isCustom;window.choiceAnswerText=customText;
  const baseHas=duoHasAnswer;duoHasAnswer=v=>isCustom(v)?!!customText(v):baseHas(v);
  const baseLabel=answerLabel;answerLabel=function(q,i){const v=state.answers?.[key(q.id,i)];return q?.type==='choice'&&isCustom(v)?customText(v)||'未作答':baseLabel(q,i)};
  const baseFormat=duoFormatAnswer;duoFormatAnswer=function(q,i,v){if(q?.type==='choice'&&isCustom(v))return customText(v)||'未作答';if(q?.id==='who'&&(v===0||v===1)&&typeof duoStableRoleName==='function')return `${v===0?'A':'B'} · ${duoStableRoleName(v)}`;return baseFormat(q,i,v)};

  window.duoStablePresenceFresh=function(id,now=Date.now()){const p=duo.presence.get(id);return !!(p&&p.online!==false&&now-(Number(p.onlineAt)||0)<ONLINE_MS)};
  window.duoStableClaimFresh=function(c,now=Date.now()){if(!c?.clientId)return false;if(c.clientId===duo.clientId)return true;return duoStablePresenceFresh(c.clientId,now)||now-(Number(c.claimedAt)||0)<STALE_CLAIM};
  window.duoStableMemberName=id=>id?(duo.states.get(id)?.nickname||duo.claims.get(id)?.nickname||(id===duo.clientId?duo.nickname:'')):'';
  window.duoStableRoleName=i=>{const id=duo.acceptedIds[i];return duoStableMemberName(id)||(i===0?'A 方':'等对方')};
  function clearRetained(){if(!duo.mqtt?.connected||!duo.topicBase)return;for(const kind of ['claim','state','presence'])duo.mqtt.publish(`${duo.topicBase}/${kind}/${duo.clientId}`,'',{retain:true})}
  duoPartnerOnline=function(){const id=duo.acceptedIds?.find(x=>x!==duo.clientId),p=id?duo.presence.get(id):null;return !!(p&&p.online!==false&&Date.now()-(Number(p.onlineAt)||0)<ONLINE_MS)};
  duoPublishClaim=async()=>duoPublish(`claim/${duo.clientId}`,{v:1,kind:'claim',clientId:duo.clientId,nickname:duo.nickname,joinedAt:duo.joinedAt,claimedAt:Date.now()},true);
  duoResolveSeats=function(){clearTimeout(duo.seatTimer);duo.seatTimer=setTimeout(()=>{const now=Date.now();for(const [id,c] of duo.claims)if(id!==duo.clientId&&!duoStableClaimFresh(c,now)){duo.claims.delete(id);duo.states.delete(id);if(!duoStablePresenceFresh(id,now))duo.presence.delete(id)}const claims=[...duo.claims.values()].filter(c=>duoStableClaimFresh(c,now)).sort((a,b)=>(a.joinedAt||0)-(b.joinedAt||0)||String(a.clientId).localeCompare(String(b.clientId)));duo.acceptedIds=claims.slice(0,2).map(x=>x.clientId);const was=duo.accepted;duo.accepted=duo.acceptedIds.includes(duo.clientId);duo.full=!duo.accepted&&claims.some(x=>x.clientId===duo.clientId);if(duo.full){duoShowFull();return}if(duo.accepted&&!was){duoPublishState().catch(()=>{});duoPublishPresence(true).catch(()=>{})}duoRefreshUI()},650)};
  function notePartner(online){if(lastPartner===null){lastPartner=online;if(online)seenPartner=true;return}if(online===lastPartner)return;const was=lastPartner;lastPartner=online;if(online){const had=seenPartner;seenPartner=true;if(was===false&&had){const n=duoRemoteNickname();showToast(`${n&&n!=='对方'?n:'TA'} 回来了`);try{window.dispatchEvent(new CustomEvent('couplequiz:partner-returned'))}catch{}}}}
  function beat(force=false){if(!duo.active||!duo.accepted||!duo.mqtt?.connected||document.visibilityState!=='visible')return;const now=Date.now();if(force||now-lastBeat>=HEARTBEAT){lastBeat=now;duoPublishPresence(true).catch(()=>{})}if(force||now-lastClaim>=30000){lastClaim=now;duoPublishClaim().catch(()=>{})}}
  duoStartPresence=function(){clearInterval(duo.presenceTimer);beat(true);duo.presenceTimer=setInterval(()=>beat(false),HEARTBEAT)};

  const baseLocalState=duoLocalState;
  duoLocalState=function(){const s={...baseLocalState(),answers:state.answers||{},rank:{},nav:duoNavPayload(),pendingKey:pendingKey()};delete s.drafts;if(!s.pendingKey)delete s.pendingKey;return s};

  window.duoNavValidQuiz=id=>!!(id&&quiz(id));
  window.duoNavNormalize=function(view,qid=null,index=0){if((view==='quiz'||view==='result')&&duoNavValidQuiz(qid)){const q=quiz(qid);return {view,quizId:qid,index:Math.max(0,Math.min(Number(index)||0,q.questions.length-1))}}return {view:'home',quizId:null,index:0}};
  window.duoNavVersion=n=>({clock:Number(n?.clock)||0,clientId:String(n?.clientId||'')});
  window.duoNavVersionNewer=(a,b)=>a.clock>b.clock||(a.clock===b.clock&&a.clientId>b.clientId);
  window.duoNavRemember=(view,qid=null,index=0)=>{duoNavWanted=duoNavNormalize(view,qid,index)};
  window.duoNavFromSnapshot=s=>s?.nav||(s?.currentQuiz?{view:'quiz',quizId:s.currentQuiz,index:s.index||0,clock:0,clientId:s.clientId}:null);
  window.duoNavPayload=()=>({view:duoNavWanted.view,quizId:duoNavWanted.quizId,index:duoNavWanted.index,clock:duoNavApplied.clock,clientId:duoNavApplied.clientId||''});
  window.duoNavFlush=function(){if(!duoNavDirty||!duo.active||!duo.accepted||!duo.mqtt?.connected)return;duoNavDirty=false;duoPublishState().catch(()=>{duoNavDirty=true})};
  window.duoNavTouch=function(view,qid=null,index=0){duoNavRemember(view,qid,index);const r=duoRemoteState(),rn=duoNavFromSnapshot(r),rc=Number(rn?.clock)||0;duoNavClock=Math.max(Date.now(),duoNavClock+1,duoNavApplied.clock+1,rc+1);duoNavApplied={clock:duoNavClock,clientId:duo.clientId};duoNavDirty=true;duoNavFlush()};
  window.duoNavQuestionDone=function(q,k,answers=state.answers,ready=null,snapshot=null){if(answers===state.answers&&pendingKey()===k)return false;if(snapshot?.pendingKey===k)return false;return duoHasAnswer(answers?.[k])};

  const coreBaseHome=typeof duoBaseHome==='function'?duoBaseHome:home;
  const coreBaseOpenQuiz=openQuiz;
  const coreBaseResult=typeof duoBaseQuizResult==='function'?duoBaseQuizResult:quizResult;
  const coreBaseRender=typeof duoBaseRenderQuestion==='function'?duoBaseRenderQuestion:renderQuestion;
  window.coreBaseHome=coreBaseHome;window.coreBaseOpenQuiz=coreBaseOpenQuiz;window.coreBaseQuizResult=coreBaseResult;

  window.duoNavApplySnapshot=function(s){if(!s||s.clientId===duo.clientId||!duo.active||!duo.accepted)return;if(!duo.acceptedIds.includes(s.clientId)||!duoPartnerOnline()||pendingKey()){duoNavPending=s;return}const nav=duoNavFromSnapshot(s);if(!nav)return;const v=duoNavVersion(nav);duoNavClock=Math.max(duoNavClock,v.clock);if(v.clock<=0||!duoNavVersionNewer(v,duoNavApplied))return;duoNavApplied=v;duoNavPending=null;const t=duoNavNormalize(nav.view,nav.quizId,nav.index);duoNavRemember(t.view,t.quizId,t.index);duoNavApplying=true;try{if(t.view==='quiz'){if(route.view!=='quiz'||route.quizId!==t.quizId||route.index!==t.index)coreBaseOpenQuiz(t.quizId,t.index)}else if(t.view==='result'){if(route.view!=='result'||route.quizId!==t.quizId)coreBaseResult(quiz(t.quizId))}else if(route.view!=='home')coreBaseHome()}finally{duoNavApplying=false}};
  window.duoNavTryPending=function(){if(duoNavPending&&duoPartnerOnline()&&duo.acceptedIds.includes(duoNavPending.clientId)&&!pendingKey()){const p=duoNavPending;duoNavPending=null;duoNavApplySnapshot(p)}};

  const resumeKey=()=>duo.active&&duo.roomId?`${RESUME_PREFIX}${duo.roomId}`:'';
  function saveRoute(){const k=resumeKey();if(!k)return;const x={view:route.view==='quiz'||route.view==='result'?route.view:'home',quizId:route.quizId||null,index:Number(route.index)||0,sessionCfg:route.quizId&&state.sessions?.[route.quizId]?JSON.parse(JSON.stringify(state.sessions[route.quizId])):null,updatedAt:Date.now()};try{localStorage.setItem(k,JSON.stringify(x))}catch{}}
  function loadRoute(){const k=resumeKey();if(!k)return null;try{const x=JSON.parse(localStorage.getItem(k)||'null');return x&&Date.now()-(Number(x.updatedAt)||0)<=RESUME_MAX?x:null}catch{return null}}
  function applySession(t){const q=t?.quizId&&quiz(t.quizId),c=t?.sessionCfg;if(!q||!c||!Array.isArray(c.indices)||!Array.isArray(q.bankQuestions)||!c.indices.length||c.indices.some(i=>!Number.isInteger(i)||i<0||i>=q.bankQuestions.length))return;if(!state.sessions||typeof state.sessions!=='object')state.sessions={};state.sessions[q.id]=JSON.parse(JSON.stringify(c));q.questions=c.indices.map(i=>q.bankQuestions[i])}
  function restoreSolo(){if(!duo.active||duoPartnerOnline()||pendingKey())return false;const x=loadRoute();if(!x)return false;applySession(x);const t=duoNavNormalize(x.view,x.quizId,x.index);duoNavApplying=true;try{duoNavRemember(t.view,t.quizId,t.index);if(t.view==='quiz'){if(route.view!=='quiz'||route.quizId!==t.quizId||route.index!==t.index)coreBaseOpenQuiz(t.quizId,t.index)}else if(t.view==='result'){if(route.view!=='result'||route.quizId!==t.quizId)coreBaseResult(quiz(t.quizId))}else if(route.view!=='home')coreBaseHome();return true}finally{duoNavApplying=false}}

  duoHandleMessage=function(topic,payload){const id=topic.split('/').pop();if(!payload?.length){if(topic.includes('/claim/'))duo.claims.delete(id);if(topic.includes('/state/'))duo.states.delete(id);if(topic.includes('/presence/'))duo.presence.delete(id);duoResolveSeats();duoRefreshUI();return}duoDecrypt(new TextDecoder().decode(payload)).then(m=>{if(!m||!m.clientId)return;if(topic.includes('/claim/')){duo.claims.set(m.clientId,m);duoResolveSeats()}else if(topic.includes('/state/')){duo.states.set(m.clientId,m);duoNavApplySnapshot(m);duoRefreshUI()}else if(topic.includes('/presence/')){duo.presence.set(m.clientId,m);duoResolveSeats();duoRefreshUI();duoNavTryPending()}})};
  duoDisconnect=async function({clearRetained:clear=duo.active}={}){connectGen++;connecting=null;clearTimeout(duo.sendTimer);clearTimeout(duo.seatTimer);clearInterval(duo.presenceTimer);clearTimeout(pendingPublishTimer);if(duo.mqtt){try{if(duo.mqtt.connected){await duoPublishPresence(false);if(clear)clearRetained()}}catch{}duo.mqtt.end()}duo.mqtt=null;duo.connected=false;duo.accepted=false;duo.full=false;duo.claims.clear();duo.states.clear();duo.presence.clear();duo.acceptedIds=[];duo.revealKey=null};
  duoConnect=function(){if(!duo.active||duo.mqtt)return connecting;if(connecting)return connecting;const gen=++connectGen,rid=duo.roomId;connecting=(async()=>{try{const will=await duoEncrypt({v:1,kind:'presence',clientId:duo.clientId,online:false,onlineAt:Date.now()});if(gen!==connectGen||!duo.active||duo.roomId!==rid||duo.mqtt)return;duo.lastError='';const cid=`cq_${duo.clientId.replace(/-/g,'').slice(0,20)}_${Math.random().toString(16).slice(2,8)}`;duo.mqtt=new TinyMQTT(DUO_WSS,{clientId:cid,username:DUO_USER,password:DUO_PASS,keepalive:30,reconnectPeriod:2500,will:{topic:`${duo.topicBase}/presence/${duo.clientId}`,payload:will,retain:true,qos:0}});duo.mqtt.subscribe(`${duo.topicBase}/claim/+`).subscribe(`${duo.topicBase}/state/+`).subscribe(`${duo.topicBase}/presence/+`);duo.mqtt.on('connect',async()=>{duo.connected=true;duo.lastError='';duoRefreshUI();await duoPublishClaim();duoResolveSeats();duoStartPresence();await duoPublishPresence(true).catch(()=>{});if(duo.accepted)await duoPublishState().catch(()=>{});scheduleResync(180)});duo.mqtt.on('message',(t,p)=>duoHandleMessage(t,p));duo.mqtt.on('close',()=>{duo.connected=false;duoRefreshUI()});duo.mqtt.on('reconnect',()=>{if(duo.mqtt){duo.connected=false;duoRefreshUI()}});duo.mqtt.on('error',()=>{duo.lastError='实时连接失败，正在重连';duoRefreshUI()})}catch{if(gen===connectGen){duo.lastError='实时连接失败，正在重连';duoRefreshUI()}}finally{if(gen===connectGen)connecting=null}})();return connecting};
  function scheduleResync(delay=160){clearTimeout(resyncTimer);resyncTimer=setTimeout(async()=>{if(!duo.active||!duo.connected||!duo.mqtt?.connected)return;await duoPublishClaim().catch(()=>{});if(!duo.accepted)return;await duoPublishPresence(true).catch(()=>{});await duoPublishState().catch(()=>{});duoNavTryPending()},delay)}

  function ensureRank(q,k,opts){const d=drafts();if(Array.isArray(d.rank[k])){state.rank[k]=[...d.rank[k]];return}if(Array.isArray(state.answers?.[k]))state.rank[k]=[...state.answers[k]];else if(!Array.isArray(state.rank[k]))state.rank[k]=[...opts]}
  moveRank=function(k,idx,dir){const a=Array.isArray(state.rank[k])?[...state.rank[k]]:[],j=idx+dir;if(j<0||j>=a.length)return;const d=drafts();[a[idx],a[j]]=[a[j],a[idx]];state.rank[k]=a;d.rank[k]=[...a];saveLocal();publishPending();renderQuestion()};
  function decorateText(q,k){const ta=app.querySelector('[data-text]');if(!ta)return;const d=drafts(),has=Object.prototype.hasOwnProperty.call(d.text,k);ta.value=has?d.text[k]:String(state.answers?.[k]??'');const b=document.createElement('button');b.type='button';b.className='answer-confirm';b.dataset.answerConfirm='text';ta.insertAdjacentElement('afterend',b);const update=()=>{const p=Object.prototype.hasOwnProperty.call(d.text,k);b.textContent=p?(duoHasAnswer(state.answers?.[k])?'确定修改':'确定答案'):'已确定';b.disabled=!p};ta.oninput=()=>{d.text[k]=ta.value;saveLocal();publishPending();update();duoDecorateQuestion();duoNavGateQuestion()};ta.addEventListener('keydown',e=>e.stopPropagation());ta.addEventListener('keyup',e=>e.stopPropagation());update();b.onclick=()=>{const raw=String(d.text[k]??ta.value);if(raw.trim())state.answers[k]=raw;else delete state.answers[k];delete d.text[k];saveLocal();save();renderQuestion()}};
  function decorateChoice(q,k){const box=app.querySelector('.question-card .options');if(!box)return;box.querySelectorAll('.letter').forEach(x=>x.remove());const d=drafts(),a=state.answers?.[k],open=!!d.customOpen[k]||isCustom(a);box.querySelector('.choice-custom-option')?.remove();if(open)box.querySelectorAll('[data-opt].selected').forEach(x=>x.classList.remove('selected'));box.querySelectorAll('[data-opt]').forEach(b=>b.onclick=()=>{delete d.custom[k];delete d.customOpen[k];state.answers[k]=Number(b.dataset.opt);saveLocal();save();renderQuestion()});if(!open){const c=document.createElement('button');c.type='button';c.className='option choice-custom-option';c.textContent='＋ 自己写一个';c.onclick=()=>{d.customOpen[k]=true;if(!Object.prototype.hasOwnProperty.call(d.custom,k))d.custom[k]=isCustom(a)?String(a.text||''):'';saveLocal();publishPending();renderQuestion();requestAnimationFrame(()=>app.querySelector('.choice-custom-editor input')?.focus())};box.appendChild(c);return}const c=document.createElement('div');c.className='option choice-custom-option choice-custom-editor selected';const raw=Object.prototype.hasOwnProperty.call(d.custom,k)?String(d.custom[k]):isCustom(a)?String(a.text||''):'';c.innerHTML=`<input type="text" maxlength="80" autocomplete="off" aria-label="自己写一个" placeholder="自己写一个…" value="${esc(raw)}"><button type="button" class="choice-custom-confirm" data-custom-confirm>确定</button>`;box.appendChild(c);const input=c.querySelector('input'),ok=c.querySelector('[data-custom-confirm]');input.oninput=()=>{d.customOpen[k]=true;d.custom[k]=input.value.slice(0,80);saveLocal();publishPending();ok.disabled=!d.custom[k].trim()};let composing=false;input.addEventListener('compositionstart',()=>{composing=true});input.addEventListener('compositionend',()=>{composing=false});input.addEventListener('keydown',e=>{e.stopPropagation();if(e.key==='Enter'&&!composing){e.preventDefault();if(!ok.disabled)ok.click()}});input.addEventListener('keyup',e=>e.stopPropagation());c.addEventListener('click',e=>{if(e.target===c)input.focus()});ok.disabled=!raw.trim();ok.onclick=e=>{e.stopPropagation();const v=String(d.custom[k]??input.value).slice(0,80);if(!v.trim()){input.focus();return}state.answers[k]={kind:CUSTOM_KIND,text:v};delete d.custom[k];d.customOpen[k]=true;saveLocal();save();renderQuestion()}};
  function decorateRank(q,k){const card=app.querySelector('.question-card');if(!card)return;card.querySelectorAll('.rank-confirm').forEach(x=>x.remove());const d=drafts(),a=Array.isArray(state.rank[k])?[...state.rank[k]]:[],old=state.answers?.[k],changed=!Array.isArray(old)||JSON.stringify(old)!==JSON.stringify(a);if(changed)d.rank[k]=[...a];else delete d.rank[k];const b=document.createElement('button');b.type='button';b.className='rank-confirm';b.textContent=changed?(Array.isArray(old)?'确定修改':'确定这个顺序'):'✓ 已确定';b.disabled=!changed;card.appendChild(b);b.onclick=()=>{state.answers[k]=[...state.rank[k]];delete d.rank[k];saveLocal();save();renderQuestion()};if(!duo.active){const next=app.querySelector('[data-next]');if(next){next.disabled=changed;if(changed)next.textContent='先确定顺序';next.onclick=()=>{if(changed)return;if(route.index===q.questions.length-1)quizResult(q);else openQuiz(q.id,route.index+1)}}}};
  function decorateControls(){if(route.view!=='quiz'||!route.quizId)return;const q=quiz(route.quizId),k=kOf(q.id,route.index);if(q.type==='text')decorateText(q,k);if(q.type==='choice')decorateChoice(q,k);if(q.type==='rank')decorateRank(q,k);if(!duo.active&&q.type!=='rank'&&pendingKey()===k){const next=app.querySelector('[data-next]');if(next){next.disabled=true;next.textContent='先确定答案';next.onclick=()=>{}}}};

  duoRelabelWho=function(){if(!duo.active||route.view!=='quiz'||route.quizId!=='who')return;const o=app.querySelectorAll('[data-opt]');if(o[0])o[0].textContent=duoStableRoleName(0);if(o[1])o[1].textContent=duoStableRoleName(1)};
  duoDecorateQuestion=function(){app.querySelector('.duo-livebar')?.remove();if(!duo.active||route.view!=='quiz')return;duoRelabelWho();const q=quiz(route.quizId),i=route.index,k=kOf(q.id,i),r=duoRemoteState(),partner=duoRemoteNickname(),lv=state.answers?.[k],rv=r?.answers?.[k],lp=pendingKey()===k,rp=r?.pendingKey===k,ld=duoHasAnswer(lv)&&!lp,rd=duoHasAnswer(rv)&&!rp;if(lp||rp)duo.revealKey=null;const bar=document.createElement('div');bar.className='duo-livebar';bar.innerHTML=`<div class="duo-live-head"><b>一起答</b><span>${duoPartnerOnline()?'在同一题':'等 TA 回来'}</span></div><div class="duo-answer-state"><div class="duo-answer-pill ${ld?'done':''}"><strong>${esc(duo.nickname)}</strong><em>${lp?'… 正在编辑':ld?'✓ 答好了':'○ 还没答'}</em></div><div class="duo-answer-pill ${rd?'done':''}"><strong>${esc(partner)}</strong><em>${rp?'… 正在编辑':rd?'✓ 答好了':duoPartnerOnline()?'○ 还没答':'○ 离线'}</em></div></div>${ld&&rd?`<button class="duo-reveal" data-duo-reveal>${duo.revealKey===k?'收起来':'都答好了 · 翻牌'}</button>`:''}<div class="duo-reveal-box"></div>`;app.querySelector('.question-card')?.appendChild(bar);if(ld&&rd)bar.querySelector('[data-duo-reveal]').onclick=()=>{duo.revealKey=duo.revealKey===k?null:k;duoDecorateQuestion()};if(duo.revealKey===k&&ld&&rd){bar.querySelector('.duo-reveal-box').innerHTML=`<div class="duo-reveal-row"><b>${esc(duo.nickname)}</b>${esc(duoFormatAnswer(q,i,lv))}</div><div class="duo-reveal-row"><b>${esc(partner)}</b>${esc(duoFormatAnswer(q,i,rv))}</div>`}};
  duoDecorateResult=function(q){if(!duo.active)return;const result=app.querySelector('.single-result');if(!result)return;const r=duoRemoteState(),partner=duoRemoteNickname();app.querySelector('.duo-result-box')?.remove();const box=document.createElement('div');box.className='duo-result-box';const done=r?q.questions.reduce((n,_,i)=>n+(duoNavQuestionDone(q,kOf(q.id,i),r.answers,r.ready,r)?1:0),0):0;box.textContent=r?`${partner} 做了 ${done}/${q.questions.length} 题${duoPartnerOnline()?' · 在线':' · 离线'}`:`等 ${partner} 开始这套`;const list=result.querySelector('.full-summary');if(list&&r)list.innerHTML=q.questions.map((it,i)=>{const k=kOf(q.id,i),lv=state.answers?.[k],rv=r.answers?.[k],ld=duoNavQuestionDone(q,k,state.answers,state.ready),rd=duoNavQuestionDone(q,k,r.answers,r.ready,r),mine=ld?duoFormatAnswer(q,i,lv):'未作答',theirs=ld&&rd?duoFormatAnswer(q,i,rv):(rd?'TA 答好了，等你':'未作答');return `<div class="summary-item duo-summary-item"><b>${i+1}. ${esc(Array.isArray(it)?it[0]:it)}</b><div class="duo-result-answers"><span><small>${esc(duo.nickname)}</small>${esc(mine)}</span><span><small>${esc(partner)}</small>${esc(theirs)}</span></div></div>`}).join('');result.insertBefore(box,list||result.querySelector('.result-actions'))};
  window.duoNavGateQuestion=function(){if(!duo.active||route.view!=='quiz')return;const q=quiz(route.quizId),k=kOf(q.id,route.index),r=duoRemoteState(),next=app.querySelector('[data-next]'),prev=app.querySelector('[data-prev]');if(!next)return;const lp=pendingKey()===k,rp=r?.pendingKey===k,ld=duoHasAnswer(state.answers?.[k])&&!lp,rd=duoHasAnswer(r?.answers?.[k])&&!rp,both=ld&&rd;if(prev){prev.disabled=route.index===0;prev.onclick=()=>{if(route.index>0)openQuiz(q.id,route.index-1)}}next.disabled=!both;if(lp)next.textContent='先确定答案';else if(!ld)next.textContent='先答这一题';else if(!duo.accepted||!r)next.textContent='等 TA 来';else if(rp)next.textContent='TA 正在编辑';else if(!rd)next.textContent='等 TA 答完';else next.textContent=route.index===q.questions.length-1?'一起看结果':'下一题';next.onclick=()=>{if(!both)return;if(route.index===q.questions.length-1)quizResult(q);else openQuiz(q.id,route.index+1)}};

  home=function(){const changed=route.view!=='home',out=coreBaseHome();if(!duoNavStarting)saveRoute();if(duo.active){duoInjectHome();duoRefreshHomeCards()}if(duo.active&&!duoNavApplying&&!duoNavStarting&&changed)duoNavTouch('home');return out};
  openQuiz=function(id,index=0){const t=duoNavNormalize('quiz',id,index),changed=route.view!=='quiz'||route.quizId!==t.quizId||route.index!==t.index,out=coreBaseOpenQuiz(t.quizId,t.index);saveRoute();if(duo.active&&!duoNavApplying&&!duoNavStarting&&changed)duoNavTouch('quiz',t.quizId,t.index);return out};
  quizResult=function(q){const changed=route.view!=='result'||route.quizId!==q.id,out=coreBaseResult(q);saveRoute();if(duo.active&&!duoNavApplying&&!duoNavStarting&&changed)duoNavTouch('result',q.id,q.questions.length-1);return out};
  renderQuestion=function(){const q=quiz(route.quizId);if(q?.type==='rank'){const item=q.questions[route.index],opts=Array.isArray(item)?item[1]:[];ensureRank(q,kOf(q.id,route.index),opts||[])}const out=coreBaseRender();decorateControls();duoDecorateQuestion();duoNavGateQuestion();return out};
  duoRefreshUI=function(){if(route.view==='home'){duoInjectHome();duoRefreshHomeCards()}else if(route.view==='quiz'){duoDecorateQuestion();duoNavGateQuestion()}else if(route.view==='result'&&route.quizId)duoDecorateResult(quiz(route.quizId));duoNavTryPending();duoNavFlush();if(duo.active)notePartner(duoPartnerOnline());else{lastPartner=null;seenPartner=false}};

  const baseActivate=duoActivate;duoActivate=async function(secret){duoNavPending=null;duoNavDirty=false;duoNavClock=0;duoNavApplied={clock:0,clientId:''};duoNavRemember('home');duoNavStarting=true;try{const out=await baseActivate(secret);setTimeout(()=>{if(!duoPartnerOnline())restoreSolo()},120);scheduleResync(900);return out}finally{duoNavStarting=false}};
  const baseLeave=duoLeaveRoom;duoLeaveRoom=async function(){clearTimeout(resyncTimer);clearTimeout(bgTimer);clearTimeout(pendingPublishTimer);lastPartner=null;seenPartner=false;lastBeat=0;lastClaim=0;return baseLeave()};
  function bgClear(){clearTimeout(bgTimer);bgTimer=null}async function bgSuspend(){bgClear();if(bgDisconnecting||bgSuspended||!duo.active||!duo.mqtt)return;bgDisconnecting=true;try{duoRoomStoreSave();await duoDisconnect({clearRetained:false});bgSuspended=true}catch{}finally{bgDisconnecting=false}}function bgSchedule(){bgClear();if(!duo.active||document.visibilityState!=='hidden')return;bgTimer=setTimeout(()=>{if(document.visibilityState==='hidden'&&duo.active)bgSuspend()},BG_GRACE)}function bgResume(){bgClear();if(!duo.active){bgSuspended=false;return}if(bgDisconnecting){setTimeout(bgResume,120);return}if(bgSuspended||!duo.mqtt){bgSuspended=false;duoConnect();duoRefreshUI()}}
  async function hidden(){lastBeat=0;saveRoute();if(duo.active&&duo.accepted&&duo.mqtt?.connected)await duoPublishPresence(false).catch(()=>{})}async function visible(){if(!duo.active)return;bgResume();if(!duo.mqtt?.connected)return;lastBeat=0;lastClaim=0;await duoPublishClaim().catch(()=>{});if(duo.accepted){await duoPublishPresence(true).catch(()=>{});lastBeat=Date.now();await duoPublishState().catch(()=>{})}duoRefreshUI();if(duoPartnerOnline())duoNavTryPending();else restoreSolo()}
  document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'){hidden();bgSchedule()}else visible()});window.addEventListener('pagehide',()=>{hidden();saveRoute()});window.addEventListener('pageshow',()=>{if(document.visibilityState==='visible')visible()});window.addEventListener('beforeunload',hidden);
  watchdog=setInterval(()=>{if(!duo.active)return;beat(false);const on=duoPartnerOnline();if(lastPartner!==null&&on!==lastPartner){duoRefreshUI();if(!on)duoResolveSeats()}else notePartner(on)},1000);
  window.addEventListener('hashchange',()=>{const secret=duoParseSecret();if(secret&&secret!==duo.roomSecret)duoJoinFromLink(secret)});

  function genCode(){const chars='abcdefghjkmnpqrstuvwxyz23456789',limit=256-(256%chars.length);let out='';while(out.length<6){for(const b of crypto.getRandomValues(new Uint8Array(8))){if(b>=limit)continue;out+=chars[b%chars.length];if(out.length===6)break}}return out}
  async function activateCode(code){const n=window.coupleRoomCode?.normalize?.(code)||String(code||'').toLowerCase(),secret=await window.coupleRoomCode.deriveSecret(n),p=new URLSearchParams(location.hash.slice(1));p.set('rc',n);history.replaceState({},'',location.pathname+location.search+`#${p}`);try{await duoActivate(secret);if(route.view==='home')duoInjectHome()}catch(e){p.delete('rc');history.replaceState({},'',location.pathname+location.search+(p.toString()?`#${p}`:''));throw e}}
  function patchRoom(){if(!window.coupleRoomCode)return;window.coupleRoomCode.generate=genCode;duoCreateRoom=function(){const code=genCode(),go=()=>activateCode(code).catch(()=>showToast('房间创建失败，请再试一次'));if(duo.nickname)go();else duoAskNickname({title:'创建双人房间',message:'输入你的昵称',confirmText:'创建房间',onDone:go})};if(route.view==='home')duoInjectHome()}
  function migrateText(){if(!state.ready||typeof state.ready!=='object')return;const d=drafts();let changed=false;for(const q of QUIZZES){if(q.type!=='text')continue;const total=Math.max(q.questions?.length||0,q.bankQuestions?.length||0);for(let i=0;i<total;i++){const k=kOf(q.id,i);if(duoHasAnswer(state.answers?.[k])&&state.ready[k]===false){if(!Object.prototype.hasOwnProperty.call(d.text,k))d.text[k]=String(state.answers[k]);delete state.answers[k];changed=true}}}if(changed)saveLocal()}
  function patchLate(){if(typeof roundsClearQuiz==='function'&&!roundsClearQuiz.__core){const base=roundsClearQuiz;const fn=function(q){const out=base(q),d=drafts(),prefix=`${q.id}:`;for(const map of [d.text,d.custom,d.customOpen,d.rank])for(const k of Object.keys(map))if(k.startsWith(prefix))delete map[k];saveLocal();return out};fn.__core=true;roundsClearQuiz=fn}}
  results=function(){home()};exportJSON=function(){};copyText=async function(){};buildExport=function(){return null};
  function boot(){patchRoom();patchLate();migrateText();if(route.view==='home')home();else if(route.view==='quiz')renderQuestion();if(duo.active&&!duoPartnerOnline())restoreSolo();requestAnimationFrame(()=>{document.documentElement.classList.add('app-ready');document.documentElement.classList.remove('app-preparing')})}
  window.coupleCore={boot,drafts,pendingKey,saveLocal,restoreSoloRoute:restoreSolo};
})();